FROM bbk/wildfly

# Temporarily overwrite dbcr jar with the newest version.
# We need custom delimiters...
#COPY .openshift/custom/dbcr-0.0.6-jar-with-dependencies.jar /opt/eap/standalone/app/dbcr.jar