DROP TABLE IF EXISTS Member;
DROP SEQUENCE IF EXISTS MEMBER_SEQ;

CREATE TABLE Member (
  ID INTEGER NOT NULL ,
  MEMBERSHIP_NUMBER VARCHAR(256) NOT NULL,
  FIRST_NAME VARCHAR(256) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  VERSION BIGINT,
  PRIMARY KEY(ID),
  UNIQUE (MEMBERSHIP_NUMBER)
);

CREATE SEQUENCE MEMBER_SEQ START WITH 1;
CREATE INDEX idx_membership_no ON Member (MEMBERSHIP_NUMBER);

